In [1]:
import os
import pandas as pd

In [2]:
df_list = []
for pqt_file in os.listdir('data/'):
    if pqt_file.endswith('.parquet'):
        df = pd.read_parquet(os.path.join('data/', pqt_file))
        print(f'{pqt_file}: {len(df)} rows')
        df_list.append(df)

base_ind_2023.parquet: 193382 rows
base_ind_2005.parquet: 188755 rows
base_ind_2015.parquet: 120173 rows
base_ind_2014.parquet: 241181 rows
base_ind_2004.parquet: 187930 rows
base_ind_2022.parquet: 198097 rows
base_ind_2006.parquet: 222968 rows
base_ind_2016.parquet: 177515 rows
base_ind_2020.parquet: 174227 rows
base_ind_2021.parquet: 192600 rows
base_ind_2017.parquet: 235332 rows
base_ind_2007.parquet: 188433 rows
base_ind_2012.parquet: 223622 rows
base_ind_2024.parquet: 187625 rows
base_ind_2025.parquet: 136457 rows
base_ind_2013.parquet: 222230 rows
base_ind_2018.parquet: 230083 rows
base_ind_2008.parquet: 247819 rows
base_ind_2011.parquet: 231657 rows
base_ind_2010.parquet: 237055 rows
base_ind_2009.parquet: 240967 rows
base_ind_2019.parquet: 234375 rows

In [3]:
base_full = pd.concat(df_list)
base_full.info()

<class 'pandas.DataFrame'>
Index: 4512483 entries, 0 to 234374
Data columns (total 32 columns):
 #   Column               Dtype
---  ------               -----
 0   CODUSU               str
 1   NRO_HOGAR            float64
 2   COMPONENTE           float64
 3   ANO4                 float64
 4   TRIMESTRE            float64
 5   REGION               float64
 6   PONDERA              float64
 7   PONDII               float64
 8   PONDIIO              float64
 9   CH04                 float64
 10  CH06                 float64
 11  NIVEL_ED             float64
 12  ESTADO               float64
 13  CAT_OCUP             float64
 14  CAT_INAC             float64
 15  P21                  float64
 16  P47T                 float64
 17  PP04B_COD            str
 18  PP04D_COD            str
 19  caes_version         str
 20  PP04B_label          str
 21  caes_seccion_cod     str
 22  caes_seccion_label   str
 23  caes_division_cod    str
 24  caes_division_label  str
 25  caes_eph_cod         str
 26  caes_eph_label       category
 27  CATEGORIA            str
 28  JERARQUIA            str
 29  TECNOLOGIA           str
 30  CALIFICACION         str
 31  EMPLEO               float64
dtypes: category(1), float64(17), str(14)
memory usage: 1.7 GB

In [6]:
base_full.head()

,CODUSU,NRO_HOGAR,COMPONENTE,ANO4,TRIMESTRE,REGION,PONDERA,PONDII,PONDIIO,CH04,...,caes_seccion_label,caes_division_cod,caes_division_label,caes_eph_cod,caes_eph_label,CATEGORIA,JERARQUIA,TECNOLOGIA,CALIFICACION,EMPLEO
0,TQRMNORVWHLMKOCDEOHCH00720228,1.0,5.0,2023.0,1.0,44.0,112.0,112.0,112.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TQRMNOPSTHKMKPCDEOHCH00781447,1.0,1.0,2023.0,1.0,44.0,190.0,192.0,190.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TQRMNOQSXHMOKRCDEOHCH00803177,1.0,1.0,2023.0,1.0,44.0,134.0,135.0,124.0,2.0,...,ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SE...,84,ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SE...,8,"Administracion publica, defensa y seguridad so...","Ocupaciones de la gestión presupuestaria, cont...",Trabajadores asalariados,Operación de sistemas y equipos informatizados,Técnicos,NaN
3,TQRMNOQSXHMOKRCDEOHCH00803177,1.0,2.0,2023.0,1.0,44.0,134.0,136.0,129.0,1.0,...,COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACI...,48,"COMERCIO, EXCEPTO DE VEHÍCULOS AUTOMOTORES Y M...",4,Comercio,Ocupaciones de la comercialización directa,Trabajadores asalariados,Sin operación de máquina,Operativos,NaN
4,TQRMNOQYTHMNKSCDEOHCH00803178,1.0,1.0,2023.0,1.0,44.0,120.0,0.0,128.0,1.0,...,ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SE...,84,ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SE...,8,"Administracion publica, defensa y seguridad so...","Ocupaciones de la construcción edilicia, de ob...",Trabajadores asalariados,Operación de maquinaria y equipos electromecán...,Operativos,NaN

In [7]:
df_select = base_full[
    [
        "ANO4",
        "TRIMESTRE",
        "REGION",
        "PONDERA",
        "PONDII",
        "PONDIIO",
        "CH04",
        "CH06",
        "NIVEL_ED",
        "ESTADO",
        "CAT_OCUP",
        "CAT_INAC",
        "EMPLEO",
        "P21",
        "P47T",
        "caes_seccion_label",
        "JERARQUIA",
    ]
]

df_select.info()

<class 'pandas.DataFrame'>
Index: 4512483 entries, 0 to 234374
Data columns (total 17 columns):
 #   Column              Dtype
---  ------              -----
 0   ANO4                float64
 1   TRIMESTRE           float64
 2   REGION              float64
 3   PONDERA             float64
 4   PONDII              float64
 5   PONDIIO             float64
 6   CH04                float64
 7   CH06                float64
 8   NIVEL_ED            float64
 9   ESTADO              float64
 10  CAT_OCUP            float64
 11  CAT_INAC            float64
 12  EMPLEO              float64
 13  P21                 float64
 14  P47T                float64
 15  caes_seccion_label  str
 16  JERARQUIA           str
dtypes: float64(15), str(2)
memory usage: 743.9 MB

In [8]:
df_select.head()

,ANO4,TRIMESTRE,REGION,PONDERA,PONDII,PONDIIO,CH04,CH06,NIVEL_ED,ESTADO,CAT_OCUP,CAT_INAC,EMPLEO,P21,P47T,caes_seccion_label,JERARQUIA
0,2023.0,1.0,44.0,112.0,112.0,112.0,1.0,7.0,1.0,4.0,0.0,3.0,NaN,0.0,0.0,NaN,NaN
1,2023.0,1.0,44.0,190.0,192.0,190.0,2.0,83.0,4.0,3.0,0.0,1.0,NaN,0.0,180000.0,NaN,NaN
2,2023.0,1.0,44.0,134.0,135.0,124.0,2.0,30.0,4.0,1.0,3.0,0.0,NaN,130000.0,130000.0,ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SE...,Trabajadores asalariados
3,2023.0,1.0,44.0,134.0,136.0,129.0,1.0,32.0,4.0,1.0,3.0,0.0,NaN,160000.0,160000.0,COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACI...,Trabajadores asalariados
4,2023.0,1.0,44.0,120.0,0.0,128.0,1.0,45.0,3.0,1.0,3.0,0.0,NaN,50000.0,-9.0,ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SE...,Trabajadores asalariados

In [11]:
for c in df_select.columns:
    print(df_select[c].value_counts())

ANO4
2008.0    247819
2014.0    241181
2009.0    240967
2010.0    237055
2017.0    235332
2019.0    234375
2011.0    231657
2018.0    230083
2012.0    223622
2006.0    222968
2013.0    222230
2022.0    198097
2023.0    193382
2021.0    192600
2005.0    188755
2007.0    188433
2004.0    187930
2024.0    187625
2016.0    177515
2020.0    174227
2025.0    136457
2015.0    120173
Name: count, dtype: int64
TRIMESTRE
2.0    1192780
1.0    1132959
4.0    1098845
3.0    1087899
Name: count, dtype: int64
REGION
43.0    1357972
40.0     940573
1.0      706206
44.0     564910
41.0     492906
42.0     449916
Name: count, dtype: int64
PONDERA
115.0     15758
113.0     15752
121.0     15580
108.0     15517
105.0     15429
          ...
4053.0        1
6671.0        1
4569.0        1
5629.0        1
5416.0        1
Name: count, Length: 6383, dtype: int64
PONDII
0.0        182587
132.0        5952
131.0        5934
121.0        5910
123.0        5862
            ...
12046.0         1
12764.0         1
9858.0          1
9701.0          1
10379.0         1
Name: count, Length: 9456, dtype: int64
PONDIIO
0.0        129870
121.0        6527
131.0        6389
115.0        6387
132.0        6351
            ...
6350.0          1
11986.0         1
12053.0         1
8739.0          1
11198.0         1
Name: count, Length: 9048, dtype: int64
CH04
2.0    2348796
1.0    2163687
Name: count, dtype: int64
CH06
18.0     82022
20.0     80571
21.0     79682
19.0     79510
22.0     78885
         ...
103.0       14
104.0        4
110.0        2
108.0        1
105.0        1
Name: count, Length: 108, dtype: int64
NIVEL_ED
3.0    914833
4.0    792061
1.0    741307
2.0    642843
5.0    501215
6.0    499148
7.0    421076
Name: count, dtype: int64
ESTADO
1.0    1848135
3.0    1832718
4.0     679632
2.0     146820
0.0       5178
Name: count, dtype: int64
CAT_OCUP
0.0    2545287
3.0    1476255
2.0     394036
1.0      76076
4.0      14939
9.0       5886
Name: count, dtype: int64
CAT_INAC
0.0    2000000
3.0    1089133
1.0     547801
5.0     391561
4.0     369562
7.0      87518
6.0      19904
2.0       7002
Name: count, dtype: int64
EMPLEO
1.0    81171
2.0    62440
9.0      128
Name: count, dtype: int64
P21
 0.0        2724006
-9.0         160020
 2000.0       62175
 3000.0       55165
 1000.0       48317
             ...
 27700.0          1
 13350.0          1
 5424.0           1
 26965.0          1
 4744.0           1
Name: count, Length: 5801, dtype: int64
P47T
 0.0        1915653
-9.0         223688
 2000.0       64316
 3000.0       59004
 1000.0       53964
             ...
 13037.0          1
 5735.0           1
 5424.0           1
 35965.0          1
 4744.0           1
Name: count, Length: 16744, dtype: int64
caes_seccion_label
INDUSTRIA MANUFACTURERA                                                                                                                                 153796
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS                                                                153693
ENSEÑANZA                                                                                                                                               130345
COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACION DE VEHICULOS AUTOMOTORES, MOTOCICLETAS, EFECTOS PERSONALES Y ENSERES DOMESTICOS                        119550
ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURO SOCIAL OBLIGATORIO                                                                                    94977
CONSTRUCCIÓN                                                                                                                                             81621
ADMINISTRACION PUBLICA, DEFENSA Y SEGURIDAD SOCIAL OBLIGATORIA                                                                                           66836
ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES DE PERSONAL DOMÉSTICO; ACTIVIDADES DE LOS HOGARES COMO PRODUCTORES DE BIENES O SERVICIOS PARA USO PROPIO     59422
CONSTRUCCION                                                                                                                                             57396
SALUD HUMANA Y SERVICIOS SOCIALES                                                                                                                        50963
SERVICIOS DE HOGARES PRIVADOS QUE CONTRATAN SERVICIO DOMESTICO                                                                                           45945
SERVICIOS INMOBILIARIOS , EMPRESARIALES Y DE ALQUILER                                                                                                    39285
TRANSPORTE Y ALMACENAMIENTO                                                                                                                              38099
SERVICIOS SOCIALES Y DE SALUD                                                                                                                            36826
SERVICIO DE TRANSPORTE, DE ALMACENAMIENTO Y DE COMUNICACIONES                                                                                            36715
ALOJAMIENTO Y SERVICIOS DE COMIDAS                                                                                                                       31437
ACTIVIDADES ADMINISTRATIVAS Y SERVICIOS DE APOYO                                                                                                         31031
OTRAS ACTIVIDADES DE SERVICIOS                                                                                                                           30780
SERVICIOS COMUNITARIOS, SOCIALES Y PERSONALES N.C.P.                                                                                                     30636
ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS                                                                                                        25874
SERVICIOS DE HOTELERIA Y RESTAURANTES                                                                                                                    20144
ARTES, ENTRETENIMIENTO Y RECREACIÓN                                                                                                                      15013
ACTIVIDADES FINANCIERAS Y DE SEGUROS                                                                                                                     14482
INFORMACIÓN Y COMUNICACIÓN                                                                                                                               12312
AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA                                                                                                        9677
INTERMEDIACION FINANCIERA Y OTROS SERVICIOS FINANCIEROS                                                                                                   8792
AGRICULTURA, GANADERIA, CAZA Y SILVICULTURA                                                                                                               8391
ACTIVIDAD NO ESPECIFICADA CLARAMENTE                                                                                                                      8034
EXPLOTACIÓN DE MINAS Y CANTERAS                                                                                                                           5694
EXPLOTACION DE MINAS Y CANTERAS                                                                                                                           4792
SUMINISTRO DE AGUA; ALCANTARILLADO; GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO                                                                      4659
ELECTRICIDAD, GAS Y AGUA                                                                                                                                  4032
ACTIVIDADES INMOBILIARIAS                                                                                                                                 3921
SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO                                                                                               3728
SERVICIOS DE ORGANIZACIONES Y ORGANOS EXTRATERRITORIALES                                                                                                  1589
PESCA Y SERVICIOS CONEXOS                                                                                                                                  881
ACTIVIDADES DE ORGANIZACIONES Y ORGANISMOS EXTRATERRITORIALES                                                                                               70
Name: count, dtype: int64
JERARQUIA
Dirección                   1430066
Trabajadores asalariados    1340446
Cuenta propia                366850
Jefes                         38891
Ns.Nc                          6416
Name: count, dtype: int64

In [13]:
df_select.sort_values(["ANO4", "TRIMESTRE"], ascending=[True, True]).head(10)

,ANO4,TRIMESTRE,REGION,PONDERA,PONDII,PONDIIO,CH04,CH06,NIVEL_ED,ESTADO,CAT_OCUP,CAT_INAC,EMPLEO,P21,P47T,caes_seccion_label,JERARQUIA
0,2004.0,1.0,43.0,386.0,NaN,NaN,1.0,32.0,5.0,1.0,3.0,0.0,NaN,1440.0,3040.0,"SERVICIO DE TRANSPORTE, DE ALMACENAMIENTO Y DE...",Trabajadores asalariados
1,2004.0,1.0,43.0,386.0,NaN,NaN,2.0,30.0,4.0,3.0,0.0,4.0,NaN,0.0,0.0,NaN,NaN
2,2004.0,1.0,43.0,386.0,NaN,NaN,2.0,2.0,7.0,4.0,0.0,5.0,NaN,0.0,0.0,NaN,NaN
3,2004.0,1.0,43.0,386.0,NaN,NaN,2.0,29.0,3.0,1.0,3.0,0.0,NaN,1250.0,1915.0,SERVICIOS SOCIALES Y DE SALUD,Trabajadores asalariados
4,2004.0,1.0,43.0,386.0,NaN,NaN,1.0,4.0,7.0,4.0,0.0,5.0,NaN,0.0,0.0,NaN,NaN
5,2004.0,1.0,43.0,386.0,NaN,NaN,1.0,3.0,7.0,4.0,0.0,5.0,NaN,0.0,0.0,NaN,NaN
6,2004.0,1.0,43.0,386.0,NaN,NaN,2.0,24.0,5.0,1.0,3.0,0.0,NaN,450.0,790.0,COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACI...,Trabajadores asalariados
7,2004.0,1.0,43.0,386.0,NaN,NaN,1.0,6.0,1.0,4.0,0.0,3.0,NaN,0.0,0.0,NaN,NaN
8,2004.0,1.0,43.0,386.0,NaN,NaN,1.0,4.0,7.0,4.0,0.0,5.0,NaN,0.0,0.0,NaN,NaN
9,2004.0,1.0,43.0,386.0,NaN,NaN,1.0,51.0,3.0,1.0,2.0,0.0,NaN,1500.0,1500.0,"SERVICIO DE TRANSPORTE, DE ALMACENAMIENTO Y DE...",Cuenta propia